import { CaseStudy } from "@/types/casestudy";

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "cgs-attendance",
    title: "AI Smart Attendance System",
    client: "Chittagong Grammar School",
    tagline: "Vision-Based Biometric Verification & Absence Dispatch",
    summary:
      "Automated biometric face recognition pipeline engineered for Chittagong Grammar School, eliminating manual roll-calls with instant attendance logging, parental SMS alerts, and admin telemetry.",
    category: "AI & Agents",
    tags: ["Computer Vision", "Python", "FastAPI", "OpenCV", "SMS Gateway", "PostgreSQL"],
    metrics: "99.4% Face Match",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Sub-second multi-face batch recognition under varying lighting",
      "Automated parental SMS alerts dispatched on unverified arrival",
      "Administrative dashboard with real-time class roll audits",
    ],
    featured: true,
    badge: "INSTITUTIONAL AI",
    gradient: "from-cyan-500/20 via-blue-500/10 to-violet-500/20",
  },
  {
    id: "smart-home-security",
    title: "Smart Home Security Ecosystem",
    client: "Homeowners Security",
    tagline: "IoT + Mobile App + AI Vision Telemetry & Remote Control",
    summary:
      "Affordable residential security monitoring system integrating edge AI cameras, real-time motion detection, instant threat alerts, remote electronic door lock control, and visitor facial recognition.",
    category: "Mobile & IoT",
    tags: ["IoT", "React Native", "Python", "WebRTC", "TensorFlow Lite", "MQTT"],
    metrics: "<150ms Alert Latency",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Edge-computed motion detection with false-positive filtering",
      "Instant push notifications with high-res visitor snapshot thumbnails",
      "Remote bi-directional door lock control with cryptographic relay",
    ],
    featured: true,
    badge: "IOT + MOBILE + AI",
    gradient: "from-emerald-500/20 via-cyan-500/10 to-blue-500/20",
  },
  {
    id: "simplified-home-remodeling",
    title: "Simplified Home Remodeling",
    client: "Commercial Client",
    tagline: "Full-Stack Renovation & Instant Project Estimator",
    summary:
      "High-converting residential remodeling web platform featuring an interactive project cost calculator, material selection showcases, and direct consultation scheduling.",
    category: "Web Dev",
    tags: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Vercel"],
    metrics: "98/100 Lighthouse",
    liveUrl: "https://simplifiedhomeremodeling.vercel.app/",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Interactive multi-room renovation cost calculator",
      "High-converting inquiry funnel with automated lead capture",
      "Ultra-fast Server-Side Rendering hosted on Vercel Edge",
    ],
    featured: false,
    badge: "LIVE ON VERCEL",
    gradient: "from-amber-500/20 via-orange-500/10 to-rose-500/20",
  },
  {
    id: "ispeed-telecom",
    title: "iSpeed Broadband Portal",
    client: "Telecom & ISP",
    tagline: "Customer Billing, Bandwidth Telemetry & Network HUD",
    summary:
      "Next-generation broadband subscriber portal offering real-time bandwidth consumption graphs, instant package switching, digital invoice downloads, and an integrated admin network status dashboard.",
    category: "Admin & CRM",
    tags: ["Next.js", "React", "TypeScript", "Dashboard HUD", "Chart.js", "Tailwind CSS"],
    metrics: "40% Support Ticket Drop",
    liveUrl: "https://ispeed-delta.vercel.app/",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Live bandwidth telemetry charts with peak usage diagnostics",
      "One-click plan upgrade and automated PDF invoice generation",
      "Admin telemetry console monitoring regional node uptime",
    ],
    featured: false,
    badge: "LIVE ON VERCEL",
    gradient: "from-blue-500/20 via-indigo-500/10 to-cyan-500/20",
  },
  {
    id: "juboh-wellness",
    title: "Juboh Health & Wellness",
    client: "Consumer Health",
    tagline: "Modern E-Commerce Experience & Product Discovery",
    summary:
      "Fluid, responsive digital storefront for health and wellness essentials featuring dynamic catalog filtering, instant bundle checkout UX, and smooth animated micro-interactions.",
    category: "Web Dev",
    tags: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Framer Motion"],
    metrics: "<0.8s Interactive",
    liveUrl: "https://juboh.vercel.app/",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Zero-layout-shift catalog discovery with multi-attribute filters",
      "Optimized mobile cart drawer with instant payment checkout flow",
      "Tailored micro-animations engineered for visual delight",
    ],
    featured: false,
    badge: "LIVE ON VERCEL",
    gradient: "from-purple-500/20 via-pink-500/10 to-cyan-500/20",
  },
  {
    id: "solar-legacy",
    title: "Solar Legacy Clean Energy",
    client: "GreenTech Energy",
    tagline: "Renewable Energy Savings Calculator & Consultation Hub",
    summary:
      "CleanTech customer acquisition web app with an interactive solar kilowatt-hour calculator, financial payback estimation model, and rooftop assessment booking pipeline.",
    category: "Web Dev",
    tags: ["Next.js", "React", "TypeScript", "Financial Modeling UI", "Tailwind CSS"],
    metrics: "+65% Lead Conversion",
    liveUrl: "https://solar-legacy-beta.vercel.app/",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Dynamic solar savings and carbon offset calculation engine",
      "Interactive multi-tier residential & commercial quote selector",
      "Fast responsive lead dispatch to field technician pipelines",
    ],
    featured: false,
    badge: "LIVE ON VERCEL",
    gradient: "from-yellow-500/20 via-amber-500/10 to-emerald-500/20",
  },
  {
    id: "dr-majed-chy",
    title: "Dr. Majed Chy Clinical Portal",
    client: "Healthcare & Clinic",
    tagline: "Physician Appointment Engine & Patient Scheduling",
    summary:
      "Specialized clinical appointment booking portal and patient hub, streamlining outpatient scheduling, doctor schedule availability, and clinic profile access across mobile and web.",
    category: "Admin & CRM",
    tags: ["Next.js", "React", "TypeScript", "Healthcare UI", "Tailwind CSS"],
    metrics: "100% Zero Overlap",
    liveUrl: "https://dr-majed-chy.vercel.app/",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Intelligent time-slot booking engine with zero schedule collision",
      "Mobile-optimized patient intake and confirmation dispatch",
      "Doctor consultation credential showcase and chamber details",
    ],
    featured: false,
    badge: "LIVE ON VERCEL",
    gradient: "from-teal-500/20 via-emerald-500/10 to-cyan-500/20",
  },
  {
    id: "enterprise-crm",
    title: "Omnichannel CRM & Lead Hub",
    client: "Enterprise Automation",
    tagline: "High-Throughput Lead Routing & Deal Velocity Platform",
    summary:
      "Multi-channel customer relationship platform with automated lead ingestion, smart SLA escalation, webhook dispatchers, and conversion analytics.",
    category: "Automation",
    tags: ["Next.js", "Node.js", "PostgreSQL", "Prisma", "Webhooks", "Tailwind CSS"],
    metrics: "3.4x Deal Speed",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Automated lead scoring and round-robin sales agent assignment",
      "Real-time deal pipeline Kanban with stage velocity tracking",
      "Bi-directional webhook ingestion from ads, forms, and web apps",
    ],
    featured: false,
    badge: "ENTERPRISE",
    gradient: "from-blue-500/20 via-cyan-500/10 to-emerald-500/20",
  },
  {
    id: "autonomous-ai-agent",
    title: "Autonomous AI Agent Engine",
    client: "AI Workflow Rig",
    tagline: "Multi-Agent Orchestrator for Complex Tool Executions",
    summary:
      "Production-grade AI agent system executing multi-step autonomous tasks, tool calling (web search, API requests, code execution), and deterministic schema verification.",
    category: "AI & Agents",
    tags: ["LangChain", "OpenAI / Claude", "Python", "Vector DB", "FastAPI", "Docker"],
    metrics: "85% Ops Saved",
    githubUrl: "https://github.com/NahianBinRahman",
    highlights: [
      "Self-correcting reflection loops with verification guards",
      "Parallel tool execution with vector semantic context memory",
      "Streaming token telemetry and execution trajectory logging",
    ],
    featured: false,
    badge: "AGENTIC WORKFLOW",
    gradient: "from-violet-500/20 via-purple-500/10 to-cyan-500/20",
  },
];
