import { GitHubProfile, ProjectShowcase } from "@/types/github";

export const FALLBACK_PROFILE: GitHubProfile = {
  login: "NahianBinRahman",
  name: "Nahian Bin Rahman",
  avatar_url: "/avatar.jpg",
  bio: "AI Engineer & AI Data Trainer | Developing & evaluating Large Language Models (LLMs), prompt optimization, and high-performance full-stack architectures",
  public_repos: 20,
  followers: 12,
  following: 15,
  location: "Guangzhou, China / Bangladesh",
  blog: "https://nahianbinrahman.com",
  twitter_username: "nahianx11",
  company: "AI Research & Software Engineering",
  html_url: "https://github.com/NahianBinRahman",
  created_at: "2019-07-09T19:14:31Z",
  updated_at: "2026-09-24T17:17:41Z",
};

export const FEATURED_PROJECTS: ProjectShowcase[] = [
  {
    title: "LLM Ticket Labeling System",
    tagline: "Autonomous Support Classification Engine",
    description: "An intelligent, high-throughput customer support ticket categorization system powered by LLMs with a seamless human-in-the-loop validation pipeline, confidence thresholds, and automated triage routing.",
    tags: ["Python", "FastAPI", "OpenAI", "LangChain", "PostgreSQL", "Docker"],
    category: "AI & ML",
    featured: true,
    githubUrl: "https://github.com/NahianBinRahman/llm-ticket-labeling-system",
    liveUrl: "https://github.com/NahianBinRahman/llm-ticket-labeling-system",
    stats: {
      metrics: "94.8% Auto-Triage Accuracy",
    },
    highlights: [
      "Dynamic few-shot prompting with vector similarity retrieval",
      "Confidence-weighted human review escalation system",
      "Real-time analytics dashboard for classification drift",
    ],
    gradient: "from-cyan-500/20 via-blue-500/10 to-violet-500/20",
    glowColor: "#00E5FF",
  },
  {
    title: "Prompt Optimization & Response Benchmark",
    tagline: "LLM Evaluation & Prompt Engineering Rig",
    description: "Rigorous empirical testing framework designed to evaluate and optimize system prompts across diverse frontier LLMs. Benchmarks token efficiency, latency, reasoning depth, and deterministic response structure.",
    tags: ["Python", "PyTorch", "HuggingFace", "Streamlit", "JSON Schema"],
    category: "AI & ML",
    featured: true,
    githubUrl: "https://github.com/NahianBinRahman/prompt-optimization-llm-response-quality",
    liveUrl: "https://github.com/NahianBinRahman/prompt-optimization-llm-response-quality",
    stats: {
      metrics: "35% Token Cost Reduction",
    },
    highlights: [
      "Automated prompt ablation and sensitivity scoring",
      "Multi-model response comparison matrix (GPT-4o, Claude 3.5, Gemini)",
      "Strict schema adherence validation with zero hallucination gates",
    ],
    gradient: "from-violet-500/20 via-purple-500/10 to-emerald-500/20",
    glowColor: "#8B5CF6",
  },
  {
    title: "ShipMove TA Tracker",
    tagline: "Real-time Maritime Logistics & Fleet Telemetry",
    description: "High-performance fleet dispatch & turn-around analytics dashboard built for tracking vessel itineraries, fuel consumption, waypoint navigation alerts, and berth schedules with sub-second websocket streaming.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Node.js", "WebSockets", "Leaflet"],
    category: "Full-Stack",
    featured: true,
    githubUrl: "https://github.com/NahianBinRahman/shipmove-ta-tracker",
    liveUrl: "https://github.com/NahianBinRahman/shipmove-ta-tracker",
    stats: {
      metrics: "Sub-100ms Telemetry Sync",
    },
    highlights: [
      "Interactive high-density GIS map layers with vessel tracking",
      "Predictive turn-around delay forecasting algorithms",
      "Real-time operational alerts with geofencing triggers",
    ],
    gradient: "from-emerald-500/20 via-teal-500/10 to-cyan-500/20",
    glowColor: "#00FF9C",
  },
  {
    title: "Solar Legacy System",
    tagline: "Green Energy Estimation & ROI Calculation Suite",
    description: "Comprehensive renewable energy simulator calculating solar PV array solar irradiance, roof pitch efficiency, battery storage lifecycle, and dynamic multi-year financial ROI projections for commercial and residential estates.",
    tags: ["React", "TypeScript", "Tailwind CSS", "Recharts", "Express"],
    category: "Enterprise / Automation",
    featured: true,
    githubUrl: "https://github.com/NahianBinRahman/solar-legacy",
    liveUrl: "https://github.com/NahianBinRahman/solar-legacy",
    stats: {
      metrics: "Calculates 25-Year Yield",
    },
    highlights: [
      "Solar irradiance mathematical modelling with geo-location inputs",
      "Interactive cashflow amortization and federal tax credit calculator",
      "Instant PDF audit report generation",
    ],
    gradient: "from-cyan-500/20 via-emerald-500/10 to-blue-500/20",
    glowColor: "#00E5FF",
  },
  {
    title: "Nahian Digital Agency Core",
    tagline: "Enterprise Modern Digital Engineering Platform",
    description: "Modern digital agency web architecture built for ultra-fast performance, headless CMS integration, server-side dynamic rendering, and fluid micro-interactions.",
    tags: ["Next.js 15", "TypeScript", "Tailwind CSS", "Framer Motion", "Vercel"],
    category: "Full-Stack",
    featured: false,
    githubUrl: "https://github.com/NahianBinRahman/nahian-digital",
    liveUrl: "https://nahianbinrahman.com",
    stats: {
      metrics: "100/100 Lighthouse Performance",
    },
    highlights: [
      "Fluid kinetic typography & glassmorphism aesthetic",
      "Zero-layout-shift responsive viewport scaling",
      "Fully type-safe content pipeline",
    ],
    gradient: "from-purple-500/20 via-pink-500/10 to-cyan-500/20",
    glowColor: "#8B5CF6",
  },
  {
    title: "Tiny Notes AI",
    tagline: "Minimalist Markdown Knowledge Hub with AI Semantic Links",
    description: "High-speed developer note-taking engine with local vector embeddings, automatic bi-directional concept cross-linking, and fast fuzzy search.",
    tags: ["Python", "SQLite", "Vector Search", "FastAPI", "React"],
    category: "Creative / Tooling",
    featured: false,
    githubUrl: "https://github.com/NahianBinRahman/tiny_notes",
    liveUrl: "https://github.com/NahianBinRahman/tiny_notes",
    stats: {
      metrics: "Instant Semantic Recall",
    },
    highlights: [
      "Offline-first local embedding index",
      "Graph visualization of interrelated ideas",
      "Keyboard-first command palette workflow",
    ],
    gradient: "from-emerald-500/20 via-cyan-500/10 to-violet-500/20",
    glowColor: "#00FF9C",
  },
];

export const TECH_ECOSYSTEM = [
  {
    category: "AI / Data",
    color: "#00E5FF",
    glow: "rgba(0, 229, 255, 0.4)",
    skills: [
      { name: "Python", level: 95, icon: "Terminal", desc: "Core language for AI models, scripting & backend" },
      { name: "Machine Learning", level: 88, icon: "Cpu", desc: "Scikit-learn, classification, regression, clustering" },
      { name: "Deep Learning", level: 85, icon: "Network", desc: "Neural networks, PyTorch, model fine-tuning" },
      { name: "LLMs & Prompt Engineering", level: 92, icon: "Sparkles", desc: "OpenAI, LangChain, RAG pipelines, agents" },
      { name: "Data Science & Pandas", level: 87, icon: "Database", desc: "Exploratory data analysis, NumPy, statistics" },
    ],
  },
  {
    category: "Frontend",
    color: "#8B5CF6",
    glow: "rgba(139, 92, 246, 0.4)",
    skills: [
      { name: "React", level: 94, icon: "Atom", desc: "Component architecture, hooks, concurrent rendering" },
      { name: "Next.js 15", level: 92, icon: "Layers", desc: "App router, SSR/SSG, server actions, API routes" },
      { name: "TypeScript", level: 90, icon: "Code2", desc: "Strict type safety, generics, modern ESM" },
      { name: "Tailwind CSS", level: 95, icon: "Palette", desc: "Utility-first design systems, responsive HUDs" },
      { name: "Three.js / 3D", level: 82, icon: "Box", desc: "WebGL shaders, particle systems, interactive 3D" },
    ],
  },
  {
    category: "Backend",
    color: "#00FF9C",
    glow: "rgba(0, 255, 156, 0.4)",
    skills: [
      { name: "Node.js", level: 90, icon: "Server", desc: "Event-driven asynchronous services, runtime tooling" },
      { name: "Express / Fastify", level: 88, icon: "Workflow", desc: "RESTful endpoints, middleware, authentication" },
      { name: "APIs & WebSockets", level: 92, icon: "Radio", desc: "Real-time bi-directional streaming, GraphQL, RPC" },
      { name: "PostgreSQL & SQLite", level: 86, icon: "HardDrive", desc: "Relational modeling, indexing, ACID transactions" },
      { name: "Vector Databases", level: 84, icon: "Binary", desc: "Pinecone, ChromaDB, pgvector semantic search" },
    ],
  },
  {
    category: "Tools & Cloud",
    color: "#38BDF8",
    glow: "rgba(56, 189, 248, 0.4)",
    skills: [
      { name: "Git & GitHub", level: 94, icon: "GitBranch", desc: "Trunk-based development, CI/CD actions, PR workflows" },
      { name: "Docker", level: 85, icon: "Container", desc: "Containerization, multi-stage builds, orchestration" },
      { name: "Linux / Shell", level: 88, icon: "TerminalSquare", desc: "Debian/Ubuntu, bash scripting, server management" },
      { name: "Cloud & Vercel", level: 90, icon: "Cloud", desc: "Edge functions, AWS services, serverless deployment" },
    ],
  },
];

export const TIMELINE_EVENTS = [
  {
    year: "Oct 2025 - Present",
    badge: "Current · 1 yr",
    role: "Founder and CTO",
    company: "Nahian DeepTech",
    location: "Software Tech Park, Chattogram · Global",
    title: "Founder and CTO @ Nahian DeepTech",
    description: "Leading an AI studio designing autonomous multi-agent systems, high-performance Next.js full-stack platforms, smart IoT integrations, and enterprise automated infrastructure.",
    category: "AI & Automation",
  },
  {
    year: "Mar 2024 - Jan 2025",
    badge: "Full-time · 11 mos",
    role: "Generative AI Engineer",
    company: "Division50",
    location: "Dubai, United Arab Emirates (Remote)",
    title: "Generative AI Engineer @ Division50",
    description: "Engineered frontier LLM applications, custom RAG architectures, multi-agent automated orchestration, and enterprise prompt testing testbeds delivering autonomous workflow automations.",
    category: "Generative AI & LLMs",
  },
  {
    year: "Dec 2021 - Jan 2023",
    badge: "Freelance · 1 yr 2 mos",
    role: "Data Analyst",
    company: "Personio",
    location: "Munich, Bavaria, Germany (Remote)",
    title: "Data Analyst @ Personio",
    description: "Spearheaded advanced data intelligence, statistical analysis, telemetry pipelines, and KPI dashboarding for HR software systems. Optimized ETL workflows and derived data-driven product insights.",
    category: "Data Analytics & BI",
  },
  {
    year: "Aug 2018 - Nov 2019",
    badge: "Full-time · 1 yr 4 mos",
    role: "Robotics Vision Engineer",
    company: "Guangzhou Aobo Robotics Ltd",
    location: "Guangzhou, China",
    title: "Robotics Vision Engineer @ Guangzhou Aobo Robotics Ltd",
    description: "Developed computer vision perception pipelines, spatial sensor fusion, and embedded real-time image processing algorithms for autonomous industrial robots and smart automation hardware.",
    category: "Robotics & Computer Vision",
  },
  {
    year: "May 2016 - Jun 2018",
    badge: "Part-time · 2 yrs 2 mos",
    role: "Application Developer",
    company: "Shinetech Software Inc.",
    location: "Beijing, China",
    title: "Application Developer @ Shinetech Software Inc.",
    description: "Built scalable enterprise web applications, internal tools, and client platforms. Mastered full-stack architectures, clean coding patterns, responsive frontends, and backend API design.",
    category: "Application Development",
  },
];
